---
  - name: Check if CapKPI App exists
    stat: path="{{ bench_path }}/apps/capkpi"
    register: app

  - name: Get the CapKPI app
    command: bench get-app capkpi {{ capkpi_repo_url }} --branch {{ capkpi_branch }}
    args:
      creates: "{{ bench_path }}/apps/capkpi"
      chdir: "{{ bench_path }}"
    when: not app.stat.exists and not without_capkpi

  - name: Check whether the site already exists
    stat: path="{{ bench_path }}/sites/{{ site }}"
    register: site_folder
    when: not without_site

  - name: Create a new site
    command: "bench new-site {{ site }} --admin-password '{{ admin_password }}' --mariadb-root-password '{{ mysql_root_password }}'"
    args:
      chdir: "{{ bench_path }}"
    when: not without_site and not site_folder.stat.exists

  - name: Install CapKPI to default site
    command: "bench --site {{ site }} install-app capkpi"
    args:
      chdir: "{{ bench_path }}"
    when: not without_site and not without_capkpi
...